experiment:
  name: linearization_sweep
  checkpoint_dir: "results/BaseNet_w_checkpoints/2025-11-05_17-12-38/default"  # adjust
  thresholds: [0.01, 0.0125, 0.015, 0.025, 0.03, 0.035, 0.055]
  
# model:
#   arch: basenet18
#   width: 64

defaults:
  - dataset: cifar10           # pull in everything from configs/dataset/cifar10.yaml
  - model: basenet18
  - override hydra/job_logging: none
  - _self_